version: '3'
services:
  account:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=account
      - DB_PORT=5432
      - DB_SSL=false
    depends_on:
      - postgres
    ports:
    - "8080:8080"
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=account
    ports:
      - "5432:5432"